# Generated by Django 5.1.1 on 2024-09-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("issuer", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuer", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResearchExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("conference", models.CharField(max_length=200)),
                ("publication", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="description",
            new_name="details",
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="name",
            field=models.CharField(default="SATYA DEEP DASARI", max_length=100),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="professional_summary",
            field=models.TextField(default="exit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="cgpa",
            field=models.FloatField(default=3.73),
            preserve_default=False,
        ),
    ]
